### ISSUE TITLE
[Feature Request] Button to send cleaned image back to the input canvas

### ISSUE THREAD

**Issue by zcatharisis** [novitalabs/sd-webui-cleaner#2]
First, thanks for making this extension. It's simple to use and hassle free compared to inpainting or photoshopping.

Cleaning images sometimes isn't perfect - some blur or artifacts may be generated in the clean up process. Putting the output image through the cleaner again usually solves the problem. The issue is that it's tedious to do so: you have to save the image locally, go to the directory it's saved in, and drag it back to the input canvas. 

A simple button that can send it back to the cleaner canvas, like the ones that already exist for sending it to img2img or extras, would be really appreciated. 

Thanks again for making the extension.

**Comment by ka1tte** [comment]
Good idea, I will implement it later.

**Comment by ArnorWing** [comment]
Is it possible to have option to save in jpg and also use the original filename and also pick folder to save to?
I really like this extension. It works so much better than ACDSEE 2024 magic eraser.

**Comment by pwcarney** [comment]
Came to this repo to leave this exact comment. Glad it's already being worked on. Love the extension

**Comment by jtydhr88** [comment]
fixed here https://github.com/novitalabs/sd-webui-cleaner/pull/5

**Comment by jtydhr88** [comment]
I think this issue could be closed as well
