### ISSUE TITLE
[Feature Request] ComfyUi support please?

### ISSUE THREAD

**Issue by cian0** [novitalabs/sd-webui-cleaner#3]
Pretty pleaaaase?

**Comment by jtydhr88** [comment]
ComfyUi is another story even we use pieces of code from this repo.

**Comment by jtydhr88** [comment]
someone already implemented this feafure for ComfyUI https://github.com/hhhzzyang/Comfyui_Lama

**Comment by cian0** [comment]
awesome thanks!!
